#+title: Emacs Configuration File
#+author: Nicolai Haddal
* Aliases
** Yes/Or/No
   Simple y/or/n substiution for yes/or/no prompts
#+begin_src emacs-lisp
    (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src
* Visual and quality of life improvements
** No toolbar/menubar/scrollbar
   #+begin_src emacs-lisp
     (tool-bar-mode -1)
     (menu-bar-mode -1)
     (scroll-bar-mode -1)
     (set-fringe-mode 10)
   #+end_src
** Display relative line numbers
#+begin_src emacs-lisp
    (display-line-numbers-mode 1)
    (setq display-line-numbers 'relative)
#+end_src
** Set font
#+begin_src emacs-lisp
    (when (member "Source Code Pro" (font-family-list))
      (set-frame-font "Source Code Pro-14" t t))
#+end_src
** Autorefresh dired
   #+begin_src emacs-lisp
     (add-hook 'dired-mode-hook 'auto-revert-mode)
   #+end_src
** Space in minibuffer
Don't use the spacebar for auto-completion in the minibuffer.
#+begin_src emacs-lisp
  (define-key minibuffer-local-completion-map (kbd "SPC") 'self-insert-command)
#+end_src
** Handle backup files
Place backup files in their own directory.
#+begin_src emacs-lisp
  (setq backup-directory-alist '(("." . "~/.emacs.d/backup"))
       backup-by-copying t  ; don't delink hardlinks
       delete-old-versions t  ; automatically delete excess backups
       )
#+end_src
** Display the time
   #+begin_src emacs-lisp
     (setq display-time-24hr-format t)
     (display-time-mode 1)
   #+end_src
** Inhibit default splashcreen
   #+begin_src emacs-lisp
     (setq inhibit-startup-message t)
   #+end_src

** Logical scrolling
   More intuitive scrolling behavior when using C+n
   #+begin_src emacs-lisp
     (setq scroll-conservatively 100)
   #+end_src
** Turn off the bell
   #+begin_src emacs-lisp
     (setq ring-bell-function 'ignore)
   #+end_src
** Prettify symbols
   #+begin_src emacs-lisp
     (when window-system(global-prettify-symbols-mode t))
   #+end_src
** Window-splitting
   Custom function for following split windows
   #+begin_src emacs-lisp
     (defun split-and-follow-horizontally ()
       (interactive)
       (split-window-below)
       (balance-windows)
       (other-window 1))
     (global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)

     (defun split-and-follow-vertically ()
       (interactive)
       (split-window-right)
       (balance-windows)
       (other-window 1))
     (global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
   #+end_src
** Subword navigation
   Navigate to first uppercase within words for e.g. camelcase words
   #+begin_src emacs-lisp
     (global-subword-mode 1)
   #+end_src
** Ignore case for completion
#+begin_src emacs-lisp
  (setq completion-ignore-case  t)
#+end_src
** electric parentheses
   auto-complete parentheses
   #+begin_src emacs-lisp
     (setq electric-pair-pairs '(
				    (?\{ . ?\})
				    (?\( . ?\))
				    (?\[ . ?\])
				    (?\" . ?\")
				    ))
     (electric-pair-mode t)
   #+end_src
** diminish
Hide certain minor modes in the status bar.
   #+begin_src emacs-lisp
     (use-package diminish
       :ensure t
       :config       (diminish 'hungry-delete-mode)
       (diminish 'beacon-mode)
       (diminish 'which-key-mode)
       (diminish 'rainbow-mode)
       (diminish 'subword-mode))
   #+end_src
** Line wrapping and word breaking
   #+begin_src emacs-lisp
     (setq org-startup-truncated nil)
   #+end_src

** Mac-specific setings
   Set modifier key.
   #+begin_src emacs-lisp
     (when (eq system-type 'darwin)
       (setq mac-right-option-modifier 'none)
       (setq mac-command-modifier 'meta))
   #+end_src

** Symlinked files
Don't warn for following symlinked files.
#+begin_src emacs-lisp
  (setq vc-follow-symlinks t)
#+end_src
** Large files
Don't warn for large files.
#+begin_src emacs-lisp
  (setq large-file-warning-threshold nil)
#+end_src
* Org-mode
** Global keybindings
   Global keybindings for org-mode for org-store-link, agenda, and capture
   #+begin_src emacs-lisp
     (global-set-key (kbd "C-c l") #'org-store-link)
     (global-set-key (kbd "C-c a") #'org-agenda)
     (global-set-key (kbd "C-c c") #'org-capture)
   #+end_src
** Capture templates
#+begin_src emacs-lisp
  (setq org-capture-templates
     '(("p" "Personal templates")
       ("pt" "TODO entry" entry
	(file+headline "~/Dropbox/Notes/personal.org" "Capture")
	(file "~/Dropbox/org/tpl-todo.txt"))
       ("pj" "Journal entry" entry
	(file+olp+datetree "~/Dropbox/org/journal.org")
	"* %U - %^{Activity}")
       ("pg" "Guitar journal entry" entry
	(file+olp+datetree "~/Dropbox/Guitar/guitar_diary.org")
	"* %U - %^{Activity}")
       ("w" "Work templates")
       ("wt" "TODO entry" entry
	(file+headline "~/Dropbox/Notes/CHN.org" "Capture")
	(file "~/Dropbox/org/tpl-todo.txt"))
       ("wh" "Heroes TODO entry" entry
	(file+headline "~/Dropbox/Work/2022 Human Needs Hero/2022_Human_Needs_Hero_Notes.org" "Capture")
	(file "~/Dropbox/org/tpl-todo.txt"))
       ("ww" "Webinar entry" entry
	(file+headline "~/Dropbox/Notes/CHN.org" "Capture")
	(file "~/Dropbox/org/webinar-todo.txt"))))
#+end_src
** Multi-state workflow
   #+begin_src emacs-lisp
     (setq org-todo-keywords
	   '((sequence "TODO(t)" "WAITING(w)" "REPEATING" "|" "DONE" "DELEGATED")))
   #+end_src
** Timestamps for closed todo items
   #+begin_src emacs-lisp
     (setq org-log-done 'time)
   #+end_src
** Set directory for org-capture
   #+begin_src emacs-lisp
     (setq org-directory "~/Dropbox/Notes")
     (setq org-default-notes-file (concat org-directory "/notes.org"))
   #+end_src
** Org-roam
   #+begin_src emacs-lisp
     (use-package org-roam
       :ensure t
       :config
       (setq org-roam-directory (file-truename "~/Dropbox/org-roam"))
       (org-roam-db-autosync-mode)
       (add-to-list 'display-buffer-alist
		       '("\\*org-roam\\*"
			 (display-buffer-in-direction)
			 (direction . right)
			 (window-width . 0.33)
			 (window-height . fit-window-to-buffer)))
       (setq org-roam-mode-section-functions
		(list #'org-roam-backlinks-section
		      #'org-roam-reflinks-section
		      ;; #'org-roam-unlinked-references-section
		      ))
       :bind (("C-c n l" . org-roam-buffer-toggle)
	      ("C-c n f" . org-roam-node-find)
	      ("C-c n i" . org-roam-node-insert)
	      ("C-c n c" . org-roam-capture)
	      :map org-mode-map
	      ("C-M-i" . completion-at-point)))
   #+end_src
** Set timer sound
   #+begin_src emacs-lisp
	  (setq org-clock-sound "~/Dropbox/yousuffer.wav")
   #+end_src
** Custom agenda views
#+begin_src emacs-lisp
  (defun org-focus-private() "Set focus on private things." (interactive)
  (setq org-agenda-files '("~/Dropbox/Notes/personal.org")))
  (defun org-focus-work() "Set focus on work things." (interactive)
  (setq org-agenda-files '("~/Dropbox/Notes/CHN.org")))
  (defun org-focus-all() "Set focus on all things." (interactive)
  (setq org-agenda-files '("~/Dropbox/Notes/personal.org" "~/Dropbox/Notes/CHN.org")))
#+end_src

** Org Babel
Configure Babel for use with Python
#+begin_src emacs-lisp
  ;; active Babel languages
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((python . t)))
#+end_src

** Auto bulleted lists
Use more normal behavior for lists in org mode
#+begin_src emacs-lisp
  (use-package org-autolist
    :ensure t
    :hook (org-mode . org-autolist-mode))
#+end_src
* Packages
** Visual improvements
*** Which-key
Which-key provides a helpful context menu whenever chords are engaged.
#+begin_src emacs-lisp
  (use-package which-key
    :ensure t
    :init
    (which-key-mode))
#+end_src
*** Beacon
    Beacon shows you where your cursor is located when you switch to a buffer.
    #+begin_src emacs-lisp
      (use-package beacon
	:ensure t
	:init
	(beacon-mode 1))
    #+end_src
** zen mode
   #+begin_src emacs-lisp
     (use-package zen-mode
       :ensure t
       :init
       (require 'zen-mode))
   #+end_src
** google translate
   #+begin_src emacs-lisp

     (use-package google-translate
       :ensure t
       :init
       (require 'google-translate)

       :functions (my-google-translate-at-point google-translate--search-tkk)
       :custom
       (google-translate-backend-method 'curl)
       :config
       (defun google-translate--search-tkk () "Search TKK." (list 430675 2721866130))
       (defun my-google-translate-at-point()
	 "reverse translate if prefix"
	 (interactive)
	 (if current-prefix-arg
	     (google-translate-at-point)
	   (google-translate-at-point-reverse)))
       :bind
       ("C-c t". my-google-translate-at-point))
   #+end_src
** evil-mode

#+begin_src emacs-lisp
    (use-package evil
    :ensure t
    :init
    (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
    (setq evil-want-keybinding nil)
    :config
    )

  (evil-mode)

  (use-package evil-collection
    :after evil
    :ensure t
    :config
    (evil-collection-init))

  ;; undo please!


  ;; emulate the brilliant vim surround plugin
  (use-package evil-surround
  :ensure t
  :config
  (global-evil-surround-mode 1))

#+end_src
** undo tree
#+begin_src emacs-lisp
  (use-package undo-tree
    :ensure t
    :after evil
    :diminish
    :config
    (evil-set-undo-system 'undo-tree)
    (global-undo-tree-mode 1))
  ;; Prevent undo tree files from polluting your git repo
  (setq undo-tree-history-directory-alist '(("." . "~/.emacs.d/undo")))
#+end_src

** elfeed
   Read RSS using elfeed.
   #+begin_src emacs-lisp
     (use-package elfeed
       :ensure t
       :config
       (setq elfeed-feeds
	     '(
	       ;;programming
	       ("https://www.reddit.com/r/emacs.rss" emacs)
	       ;;news
	       ("http://feeds.bbci.co.uk/news/world/rss.xml" bbc)
	       ("http://www.npr.org/rss/rss.php?id=1004" npr)
	       ;;po polsku
	       ("https://www.polsatnews.pl/rss/polska.xml" polsat)
	       ))
       (setq-default elfeed-search-filter "@2-days-ago +unread")  
       (setq-default elfeed-search-title-max-width 100)           
       (setq-default elfeed-search-title-min-width 100))
   #+end_src
** CSV mode
   #+begin_src emacs-lisp
     (use-package csv-mode
       :ensure t)
   #+end_src
** read epubs
   #+begin_src emacs-lisp
     (use-package nov
       :ensure t
       :config
       (add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode)))
   #+end_src
** pop-up kill ring
   A nice pop-up that lets you navigate through your killring history.
   #+begin_src emacs-lisp
     (use-package popup-kill-ring
       :ensure t
       :bind ("M-y" . popup-kill-ring))
   #+end_src
** Dashboard
   #+begin_src emacs-lisp
     (use-package dashboard
       :ensure t
       :config
       (dashboard-setup-startup-hook)
       (setq dashboard-items '((recents . 5)
			       (agenda . 10)
			       (bookmarks . 5)
			       (projects . 5)))
       (setq dashboard-startup-banner "~/Pictures/pic2.png")
       (setq dashboard-banner-logo-title "Welcome to Emacs!"))
   #+end_src
** Dired
   Optimized configuration for file management in Emacs.
   #+begin_src emacs-lisp
     (use-package dired
       :ensure nil
       :custom
       (when (eq system-type 'darwin)
	 ((insert-directory-program "gls" dired-use-ls-dired t)
		(dired-listing-switches "-agho --group-directories-first")))
       :config
       )
   #+end_src
** IDO
*** Enable IDO
   #+begin_src emacs-lisp
     (setq ido-enable-flex-matching nil)
     (setq ido-create-new-buffer 'always)
     (setq ido-everywhere t)
     (ido-mode 1)
   #+end_src
*** id-vertical
    #+begin_src emacs-lisp
      (use-package ido-vertical-mode
	:ensure t
	:init
	(ido-vertical-mode 1))
      (setq ido-vertical-define-keys 'C-n-and-C-p-only)
    #+end_src
** smex
    ido-like behavior for M-x. remembers your most frequently called commands.
    #+begin_src emacs-lisp
      (use-package smex
	:ensure t
	:init (smex-initialize)
	:bind
	("M-x" . smex))
    #+end_src
** avy
   #+begin_src emacs-lisp 
     (use-package avy
       :ensure t
       :bind
       ("M-s" . avy-goto-char))
   #+end_src
** switch-window
   Better window switching.
   #+begin_src emacs-lisp
     (use-package switch-window
       :ensure t
       :config
	 (setq switch-window-input-style 'minibuffer)
	 (setq switch-window-increase 4)
	 (setq switch-window-threshold 2)
	 (setq switch-window-shortcut-style 'qwerty)
	 (setq switch-window-qwerty-shortcuts
	     '("a" "s" "d" "f" "j" "k" "l" "i" "o"))
       :bind
	 ([remap other-window] . switch-window))
   #+end_src
** Flycheck
   Improved syntax checking
   #+begin_src emacs-lisp
	  (use-package flycheck
	    :ensure t
	  )
   #+end_src
** hungry-delete
   Hungry delete whitespace
   #+begin_src emacs-lisp
     (use-package hungry-delete
       :ensure t
       :config (global-hungry-delete-mode))
   #+end_src
** sudo-edit
   Edit 
   #+begin_src emacs-lisp
     (use-package sudo-edit
       :ensure t
       )
   #+end_src
** rainbow-delimiters
   #+begin_src emacs-lisp
     (use-package rainbow-delimiters
       :ensure t
       :init
       (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
   #+end_src
** all-the-icons
   #+begin_src emacs-lisp
     (use-package all-the-icons
       :ensure t
       :if (display-graphic-p))

   #+end_src
** company
   Company mode is an extension that allows for autocompletion.
   #+begin_src emacs-lisp
     (use-package company
       :ensure t
       :init
       (add-hook 'after-init-hook 'global-company-mode))
   #+end_src
*** company quick-help mode
   #+begin_src emacs-lisp
     (use-package company-quickhelp
       :ensure t
       :init
       (company-quickhelp-mode))
   #+end_src
** projectile
   #+begin_src emacs-lisp
     (use-package projectile
       :ensure t)
     (projectile-mode +1)
     (define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
     (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
   #+end_src
** Multiple Cursors
   Select multiple instances of the same selection. Super useful for replacing variables.
   #+begin_src emacs-lisp
     (use-package multiple-cursors
      :ensure t
      :bind ("C-c q" . 'mark-next-like-this))
#+end_src
** expand-region
   Expand your selection by region with C-q! 
   #+begin_src emacs-lisp
     (use-package expand-region
       :ensure t
       :bind ("C-q" . er/expand-region))
   #+end_src
** magit
   Git management.
   #+begin_src emacs-lisp
     (use-package magit
       :ensure t)
   #+end_src
** olivetti
   Nice, centered mode for reading text.
   #+begin_src emacs-lisp
     (use-package olivetti
       :ensure t
       )
     (add-hook 'olivetti-mode-hook 'my-buffer-face-mode-serif)
   #+end_src
** HTMLize
We install this package so org-mode will export HTML files with syntax highlighting within code blocks.
#+begin_src emacs-lisp
  (use-package htmlize
    :ensure t)
#+end_src

* Buffers
** enable ibuffer
   #+begin_src emacs-lisp
     ; (global-set-key (kbd "C-x b") 'ibuffer)
   #+end_src
   
* Custom functions
** config edit/reload
*** edit
   #+begin_src emacs-lisp
     (defun config-visit()
       (interactive)
       (find-file "~/.emacs.d/config.org"))
     (global-set-key (kbd "C-c e") 'config-visit)
   #+end_src
*** reload
    #+begin_src emacs-lisp
      (defun config-reload ()
	(interactive)
	(org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
      (global-set-key (kbd "C-c r") 'config-reload)
    #+end_src
** Yank whole line
   #+begin_src emacs-lisp
     (defun copy-whole-line()
       (interactive)
       (save-excursion
	 (kill-new
	  (buffer-substring
	   (point-at-bol)
	   (point-at-eol)))))
     (global-set-key (kbd "C-c w l") 'copy-whole-line)
   #+end_src
   
** Insert elisp in org mode
   #+begin_src emacs-lisp
     (fset 'insertelisporg
	(kmacro-lambda-form [?< ?\C-d ?s tab ?e ?m ?a ?c ?s ?- ?l ?i ?s ?p ?\C-n ?\C-c ?\'] 0 "%d"))
     (global-set-key (kbd "<f8>") 'insertelisporg)
   #+end_src   
* Diary
** Diary directory
  Set a different directory for the diary file.
  #+begin_src emacs-lisp
    (setq diary-file "~/Dropbox/diaryfile.org")
  #+end_src
** Org journal
Use org journal for day-to-day journal entries.
#+begin_src emacs-lisp
  (use-package org-journal
    :ensure t
    :defer t
    :init
    ;; Change default prefix key; needs to be set before loading org-journal
    (setq org-journal-prefix-key "C-c j")
    :config
    (setq org-journal-dir "~/Dropbox/org/journal/"
	  org-journal-date-format "%A, %d %B %Y"))
  ;; The built-in calendar mode mappings for org-journal
  ;; conflict with evil bindings
#+end_src
* Word processing

** Flyspell configuration
   Spell-checking with flyspell. Enable for all text modes.
   #+begin_src emacs-lisp
     (dolist (hook '(text-mode-hook))
       (add-hook hook (lambda () (flyspell-mode 1))))
     (eval-after-load "flyspell"
       '(progn
	  (define-key flyspell-mouse-map [down-mouse-3] #'flyspell-correct-word)
	  (define-key flyspell-mouse-map [mouse-3] #'undefined)))
   #+end_src

* Doom modeline
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1))
#+end_src
* Support for markdown mode
#+begin_src emacs-lisp
  (use-package markdown-mode
    :ensure t
    :mode ("README\\.md\\'" . gfm-mode)
    :init (setq markdown-command "pandoc"))
#+end_src
* Wrap Region
Wrap selection automatically with a quote, parenthesis, curly brackets.
#+begin_src emacs-lisp
  (use-package wrap-region
    :ensure t
    :config
    (wrap-region-mode t))
#+end_src
* Change a word with visual feedback
One of the nice features I've seen in non-Emacs editors is the ability to change variables with visual feedback.
Activate with C-;
#+begin_src emacs-lisp
  (use-package iedit
    :ensure t)
#+end_src
* Theme
** Doom themes
#+begin_src emacs-lisp
  (use-package doom-themes
    :ensure t)
  (use-package emacs
    :init
    :config
    (load-theme 'doom-one t))
#+end_src
* Enable wrap-region by default
Allows us to surround text with e.g. quotation marks.
#+begin_src emacs-lisp
  (wrap-region-mode t)
#+end_src
* YASnippet
#+begin_src emacs-lisp
  (use-package yasnippet
    :ensure t)
  (yas-reload-all)
  (add-hook 'prog-mode-hook #'yas-minor-mode)

  ;; We need to install snippets separately
  (use-package yasnippet-snippets
    :ensure t)
#+end_src
* IDE Features
** eglot
Minimal IDE-like features for emacs.
#+begin_src emacs-lisp
  (use-package eglot
    :ensure t)
#+end_src
** Disable python interpreter warning
#+begin_src emacs-lisp
  (setq python-shell-completion-native-disabled-interpreters '("python"))
#+end_src
* tab bar history
#+begin_src emacs-lisp
  (global-set-key (kbd "M-[") 'tab-bar-history-back)
  (global-set-key (kbd "M-]") 'tab-bar-history-forward)
#+end_src
* writeroom mode
#+begin_src emacs-lisp
  (use-package writeroom-mode
    :ensure t)
  (add-hook 'writeroom-mode-enable-hook 'my-buffer-face-mode-serif)
  (add-hook 'writeroom-mode-disable-hook 'my-buffer-face-mode-sans)
#+end_src
* Edit FF windows with Emacs
#+begin_src emacs-lisp
  (use-package edit-server
    :ensure t
    :commands edit-server-start
    :init (if after-init-time
		(edit-server-start)
	      (add-hook 'after-init-hook
			#'(lambda() (edit-server-start))))
    :config (setq edit-server-new-frame-alist
		  '((name . "Edit with Emacs FRAME")
		    (top . 200)
		    (left . 200)
		    (width . 80)
		    (height . 25)
		    (minibuffer . t)
		    (menu-bar-lines . t)
		    (window-system . x))))
#+end_src
* ivy/counsel/swiper
#+begin_src emacs-lisp
    (use-package counsel
      :ensure t)
  (ivy-mode)
  (setq ivy-use-virtual-buffers t)
  (setq enable-recursive-minibuffers t)
  ;; enable this if you want `swiper' to use it
  ;; (setq search-default-mode #'char-fold-to-regexp)
  (global-set-key "\C-s" 'swiper)
  (global-set-key (kbd "C-c C-r") 'ivy-resume)
  (global-set-key (kbd "<f6>") 'ivy-resume)
  (global-set-key (kbd "M-x") 'counsel-M-x)
  (global-set-key (kbd "C-x C-f") 'counsel-find-file)
  (global-set-key (kbd "<f1> f") 'counsel-describe-function)
  (global-set-key (kbd "<f1> v") 'counsel-describe-variable)
  (global-set-key (kbd "<f1> o") 'counsel-describe-symbol)
  (global-set-key (kbd "<f1> l") 'counsel-find-library)
  (global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
  (global-set-key (kbd "<f2> u") 'counsel-unicode-char)
  (global-set-key (kbd "C-c g") 'counsel-git)
  (global-set-key (kbd "C-c j") 'counsel-git-grep)
  (global-set-key (kbd "C-c k") 'counsel-ag)
  (global-set-key (kbd "C-x l") 'counsel-locate)
  (global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
  (define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)
#+end_src
* hydra
This is a package for GNU Emacs that can be used to tie related commands into a family of short bindings with a common prefix - a Hydra.
#+begin_src emacs-lisp
  (use-package hydra
    :ensure t)
  (load "~/.emacs.d/hydras.el")
#+end_src
* pdf tools
#+begin_src emacs-lisp
  (use-package pdf-tools
    :ensure t)
#+end_src
* vterm
Let's use a good terminal emulator in emacs!
#+begin_src emacs-lisp
    (use-package vterm
      :ensure t)
#+end_src
